### ISSUE TITLE
fix: tmai-app (Tauri) compilation error after config settings update

### ISSUE THREAD

**Issue by trust-delta** [trust-delta/tmai#242]
## Problem

After merging #241 (Orchestrator Agent settings), \`cargo build\` fails for the \`tmai-app\` crate (Tauri standalone app) with a match exhaustiveness error:

\`\`\`
error: could not compile \`tmai-app\` (bin "tmai-app") due to 1 previous error
\`\`\`

The error is likely in the settings/config handling code where a new \`[orchestrator]\` section was added to \`crates/tmai-core/src/config/settings.rs\` but the Tauri app's match arms were not updated.

## Context

- The \`tmai-app\` crate lives on \`dev/tmai-app\` branch and is included in the workspace
- Main \`tmai\` binary builds fine (\`cargo build -p tmai\` succeeds)
- This only affects \`cargo build\` without \`-p\` flag (workspace-wide build)

## Fix

Update \`tmai-app\` code to handle the new config variants, or exclude it from default workspace build if it's not actively maintained on main.

**Comment by trust-delta** [comment]
Moved to https://github.com/trust-delta/tmai-core/issues/28 as part of the repo split. Closing here to consolidate follow-up.
